package core.basesyntax;

public enum Color {
    AMARANTH, AMBER, AMETHYST, APRICOT, AQUAMARINE, AZURE, BABBLE, BEIGE,
    BRICKED, BLACK, BLUE, BLUSH, BRONZE, BROWN, BURGUNDY, BYZANTIUM, CARMINE,
    CERISE, CERULEAN, CHAMPAGNE, CHOCOLATE, COFFEE, COPPER, CORAL, CRIMSON,
    CYAN, EMERALD, ERIN, GOLD, GRAY, GREEN, HARLEQUIN, INDIGO, IVORY, JADE,
    LAVENDER, LEMON, LILAC, LIME, MAGENTA, MAROON, MAUVE, OCHRE, OLIVE, ORANGE,
    ORCHID, PEACH, PEAR, PERIWINKLE, PINK, PLUM, PURPLE, RASPBERRY, RED, ROSE,
    RUBY, SAPPHIRE, SCARLET, SILVER, TAN, TAUPE, TEAL, TURQUOISE, ULTRAMARINE,
    VIOLET, VIRIDIAN, WHITE, YELLOW
}
